name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3
        with:
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Git-Konfiguration setzen
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Upstream-Remote hinzufügen
        run: |
          git remote add upstream https://github.com/runtipi/runtipi-appstore.git || true

      - name: Upstream abrufen
        run: git fetch upstream

      - name: Rebase von upstream/master
        run: |
          git checkout master
          if ! git rebase upstream/master; then
            echo "Konflikte erkannt. Auflösen..."
            # Eigene Version von sync-fork.yml beibehalten
            git checkout --ours .github/workflows/sync-fork.yml || true
            # Für renovate.yml Version aus origin/master übernehmen
            git checkout origin/master -- .github/workflows/renovate.yml || true
            git add .github/workflows/sync-fork.yml .github/workflows/renovate.yml
            git rebase --continue
          fi

      - name: Exclude workflow changes (ohne sync-fork.yml)
        run: |
          # Alle .yml-Dateien im workflows-Ordner außer sync-fork.yml auf den Stand von origin/master zurücksetzen
          for file in $(git ls-tree -r --name-only origin/master .github/workflows | grep -v 'sync-fork.yml'); do
            git checkout origin/master -- "$file"
          done
          # Wenn es nichts zu committen gibt, soll dieser Schritt nicht fehlschlagen
          git commit --amend --no-edit || true

      - name: Änderungen pushen
        run: |
          git push origin master --force-with-lease
