name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3
        with:
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Git-Konfiguration setzen
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Upstream-Remote hinzufügen
        run: |
          git remote add upstream https://github.com/runtipi/runtipi-appstore.git || true

      - name: Upstream abrufen
        run: git fetch upstream

      - name: Rebase von upstream/master
        run: |
          git checkout master
          git rebase upstream/master

      - name: Exclude workflow changes
        run: git checkout origin/master -- .github/workflows

      - name: Änderungen pushen
        run: |
          git push origin master --force-with-lease
